package org.fresnel.optics;

/** Exclusive family of parallel lines generated by a variable-line grating. */
public enum LineOrientation {
    /** Lines run along page Y; pitch changes along page X. */
    VERTICAL,
    /** Lines run along page X; pitch changes along page Y. */
    HORIZONTAL
}
